In [3]:
import numpy as np

In [5]:
array_1d = np.array([61,52.5,71,32.5,68,64]) # 1D - Array
array_2d = np.array([[18,26,17],
                     [25,15.5,12],
                     [24,27,20],
                     [10,5.5,17],
                     [27,26,15],
                     [22,21,21]])

print(type(array_1d))
print(type(array_2d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
array_1d = np.array([61,52,71,32])

print(array_1d.ndim)
print(array_1d.shape)
print(array_1d.size)
print(array_1d.dtype)

1
(4,)
4
int32


In [13]:
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d.size)
print(array_2d.dtype)

2
(6, 3)
18
float64


In [20]:
ones_2d = np.ones(shape=5)
ones_2d
print(ones_2d.dtype)

float64


In [16]:
zeros_1d = np.zeros(shape=(3,5))
zeros_1d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
range_array = np.arange(2,10,2)
range_array

array([2, 4, 6, 8])

In [12]:
array_2d = np.array([[18,26,17],
                     [25,15.5,12],
                     [24,27,20],
                     [10,5.5,17],
                     [27,26,15],
                     [22,21,21]])

print(array_2d[[0,1],[1]])

[26.  15.5]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [14]:
'''
Convert 1D array with 8 elements to 3D array with 2x2 elements:
'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [16]:
'''
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

Example
'''

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [1]:
help(str())

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  