# Python Data Types

- Text Type:	str
- Numeric Types:	int, float, complex
- Sequence Types:	list, tuple, range
- Mapping Type:	dict
- Set Types:	set, frozenset
- Boolean Type:	bool
- Binary Types:	bytes, bytearray, memoryview

In [4]:
# Python Data Types

print(type("Hello World"))
print(type(20))
print(type(20.5))
print(type(1j)) # "j" as the imaginary part
print(type(["apple", "banana", "cherry"]))
print(type(("apple", "banana", "cherry")))
print(type(range(6)))
print(type({"name" : "John", "age" : 36}))
print(type({"apple", "banana", "cherry"}))
print(type(frozenset({"apple", "banana", "cherry"})))
print(type(True))
print(type(b"Hello"))
print(type(bytearray(5)))
print(type(memoryview(bytes(5))))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'list'>
<class 'tuple'>
<class 'range'>
<class 'dict'>
<class 'set'>
<class 'frozenset'>
<class 'bool'>
<class 'bytes'>
<class 'bytearray'>
<class 'memoryview'>


# Python Numbers

In [5]:
# Python Numbers

## Type Conversion

x = 1    # int
y = 2.8  # float
z = 1j   # complex

#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)

#convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>


In [6]:
# Random Number

import random
print(random.randrange(1,10))

2


# Python Casting

- Specify a Variable Type

In [7]:
x = int(2.8)
y = float("3")
z = str(5.4)
print(x,y,z)

2 3.0 5.4


# Python Strings

In [8]:
str_single_1 = 'str' 
str_single_2 = "str"
str_double_1 = '''Lorem ipsum dolor sit amet, 
                consectetur adipiscing elit,
                sed do eiusmod tempor incididunt
                ut labore et dolore magna aliqua.'''

str_double_2 = """Lorem ipsum dolor sit amet,
                consectetur adipiscing elit,
                sed do eiusmod tempor incididunt
                ut labore et dolore magna aliqua."""

In [17]:
# Slicing
## [start:end:step] (end not included)
## Negative Indexing (starts from -1)
b = "Hello, World!"
print(b[2:5])
print(b[:5])
print(b[2:])
print(b[-1])
print(b[-5:-2])
print(b[::2])

llo
Hello
llo, World!
!
orl
Hlo ol!


In [18]:
# Modify Strings
a = "Hello, World!"
print(a.upper())
print(a.lower())
print(a.strip()) # Remove Whitespace
print(a.replace("H", "J"))
print(a.split(","))

HELLO, WORLD!
hello, world!
Hello, World!
Jello, World!
['Hello', ' World!']


In [20]:
# String Format
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 49.95 dollars for 3 pieces of item 567.


In [22]:
# Escape Character (\)

'''
\'	Single Quote	
\\	Backslash	
\n	New Line	
\r	Carriage Return	
\t	Tab	
\b	Backspace	
\f	Form Feed	
\ooo	Octal value	
\xhh	Hex value
'''

txt = "We are the so-called \"Vikings\" from the north."
print(txt)

We are the so-called "Vikings" from the north.


In [23]:
# String Methods

'''
capitalize()	Converts the first character to upper case
casefold()	Converts string into lower case
center()	Returns a centered string
count()	Returns the number of times a specified value occurs in a string
encode()	Returns an encoded version of the string
endswith()	Returns true if the string ends with the specified value
expandtabs()	Sets the tab size of the string
find()	Searches the string for a specified value and returns the position of where it was found
format()	Formats specified values in a string
format_map()	Formats specified values in a string
index()	Searches the string for a specified value and returns the position of where it was found
isalnum()	Returns True if all characters in the string are alphanumeric
isalpha()	Returns True if all characters in the string are in the alphabet
isdecimal()	Returns True if all characters in the string are decimals
isdigit()	Returns True if all characters in the string are digits
isidentifier()	Returns True if the string is an identifier
islower()	Returns True if all characters in the string are lower case
isnumeric()	Returns True if all characters in the string are numeric
isprintable()	Returns True if all characters in the string are printable
isspace()	Returns True if all characters in the string are whitespaces
istitle()	Returns True if the string follows the rules of a title
isupper()	Returns True if all characters in the string are upper case
join()	Joins the elements of an iterable to the end of the string
ljust()	Returns a left justified version of the string
lower()	Converts a string into lower case
lstrip()	Returns a left trim version of the string
maketrans()	Returns a translation table to be used in translations
partition()	Returns a tuple where the string is parted into three parts
replace()	Returns a string where a specified value is replaced with a specified value
rfind()	Searches the string for a specified value and returns the last position of where it was found
rindex()	Searches the string for a specified value and returns the last position of where it was found
rjust()	Returns a right justified version of the string
rpartition()	Returns a tuple where the string is parted into three parts
rsplit()	Splits the string at the specified separator, and returns a list
rstrip()	Returns a right trim version of the string
split()	Splits the string at the specified separator, and returns a list
splitlines()	Splits the string at line breaks and returns a list
startswith()	Returns true if the string starts with the specified value
strip()	Returns a trimmed version of the string
swapcase()	Swaps cases, lower case becomes upper case and vice versa
title()	Converts the first character of each word to upper case
translate()	Returns a translated string
upper()	Converts a string into upper case
zfill()	Fills the string with a specified number of 0 values at the beginning

'''

'''
1. rsplit() & split() difference
https://www.tutorialsteacher.com/python/string-rsplit

str.rsplit(separator, maxsplit)
The rsplit() method will raise the ValueError if a separator is an empty string ''.
'''

langs = 'C,Python,R,Java,SQL,Hadoop'
print(langs.rsplit(',', 3))

fruits = 'apples$banana$mango$fig$pear'
print(fruits.rsplit('$', 2))

['C,Python,R', 'Java', 'SQL', 'Hadoop']
['apples$banana$mango', 'fig', 'pear']


# Python Booleans

In [24]:
'''
Any string is True, except empty strings.

Any number is True, except 0.

Any list, tuple, set, and dictionary are True, except empty ones.
(), [], {}, "", the number 0, and the value None and False = False
'''

print(bool("Hello"))

True


In [25]:
class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))

False


In [26]:
def myFunction() :
  return True

print(myFunction())

True


# Python Operators

In [ ]:
# Python Arithmetric Operators

'''
Operator	Description	Example
+	Addition	x + y	
-	Subtraction	x - y	
*	Multiplication	x * y	
/	Division	x / y	
%	Modulus	x % y	
**	Exponentiation	x ** y	
//	Floor division	x // y

'''

# Python Assignment Operators

'''
Operator	Description	Example
=	x = 5	x = 5	
+=	x += 3	x = x + 3	
-=	x -= 3	x = x - 3	
*=	x *= 3	x = x * 3	
/=	x /= 3	x = x / 3	
%=	x %= 3	x = x % 3	
//=	x //= 3	x = x // 3	
**=	x **= 3	x = x ** 3	
&=	x &= 3	x = x & 3	
|=	x |= 3	x = x | 3	
^=	x ^= 3	x = x ^ 3	
>>=	x >>= 3	x = x >> 3	
<<=	x <<= 3	x = x << 3

'''

# Python Comparison Operators

'''
Operator	Description	Example
==	Equal	x == y	
!=	Not equal	x != y	
>	Greater than	x > y	
<	Less than	x < y	
>=	Greater than or equal to	x >= y	
<=	Less than or equal to	x <= y
'''

# Python Logical Operators

'''
and
or
not
'''

# Python Identity Operators

'''
Identity operators are used to compare the objects, not if they are equal, 
but if they are actually the same object, with the same memory location:

is
is not
'''

# Python Membership Operators

'''
in 
not in
'''

# Python Bitwise Operators

'''
Operator	Name	Description
& 	AND	Sets each bit to 1 if both bits are 1
|	OR	Sets each bit to 1 if one of two bits is 1
 ^	XOR	Sets each bit to 1 if only one of two bits is 1
~ 	NOT	Inverts all the bits
<<	Zero fill left shift	Shift left by pushing zeros in from the right and let the leftmost bits fall off
>>	Signed right shift	Shift right by pushing copies of the leftmost bit in from the left, and let the rightmost bits fall off

'''

In [31]:
'''
https://wiki.python.org/moin/BitwiseOperators

'''
x = 5
y = 5

x <<= 3
print(x)

y >>= 3
print(y)

40
0


# Python Collections (Arrays)
There are four collection data types in the Python programming language:

- List is a collection which is ordered and changeable. Allows duplicate members.
- Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
- Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
- Dictionary is a collection which is ordered** and changeable. No duplicate members.

*Set items are unchangeable, but you can remove and/or add items whenever you like.

**As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.

# Python Lists

In [ ]:
'''
List items are ordered, changeable, and allow duplicate values.

List items are indexed, the first item has index [0], the second item has index [1] etc.
'''

## Change/Add List Items

In [54]:
thislist = ["apple", "banana", "cherry"]
list1 = ["abc", 34, True, 40, "male"] # contain diff data types
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

## len of list
print(len(thislist))

## Indexiing of list [start:end:step] (end not included)

print(thislist[1])
print(thislist[-1])

## in
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

## Change item value
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)
thislist[1:2] = ["blackcurrant", "watermelon"]
print(thislist)

## Insert Item without replacing
thislist.insert(2, "banana")
print(thislist)

## Append to end
thislist.append("orange")
print(thislist)

## Extent List
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical) # can add any iteration objects (tuples, sets, dicts)
print(thislist)

thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

['apple', 'banana', 'cherry']
3
banana
cherry
Yes, 'apple' is in the fruits list
['apple', 'blackcurrant', 'watermelon']
['apple', 'blackcurrant', 'watermelon', 'watermelon']
['apple', 'blackcurrant', 'banana', 'watermelon', 'watermelon']
['apple', 'blackcurrant', 'banana', 'watermelon', 'watermelon', 'orange']
['apple', 'blackcurrant', 'banana', 'watermelon', 'watermelon', 'orange', 'mango', 'pineapple', 'papaya']
['apple', 'blackcurrant', 'banana', 'watermelon', 'watermelon', 'orange', 'mango', 'pineapple', 'papaya', 'kiwi', 'orange']


## Remove List Items

In [55]:
thislist = ["apple", "banana", "cherry"]

## Remove specified item
thislist.remove("banana")
print(thislist)

## Remove specified index
thislist.pop(1) # default is last item
print(thislist)

del thislist[0]
print(thislist)

# del thislist

thislist.clear()
print(thislist)

['apple', 'cherry']
['apple']
[]
[]


In [45]:
# A short hand for loop that will print all items in a list

thislist = ["apple", "banana", "cherry"]
[print(x) for x in thislist]

apple
banana
cherry


[None, None, None]

## Looping

1. For Loop with/without (len) (range)
2. While Loop

## List Comprehension

In [46]:
'''
newlist = [expression for item in iterable if condition == True]
'''

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

['apple', 'banana', 'mango']


## Sort Lists

In [52]:
## Ascending Alphanumerically
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)

thislist = [100, 50, 65, 82, 23]
thislist.sort()
print(thislist)

# Descending
thislist.sort(reverse = True)
print(thislist)

# Customize Sort Function

def myfunc(n):
  return abs(n - 50)

thislist = [100, 50, 65, 82, 23]
thislist.sort(key = myfunc)
print(thislist)

# case-insensitive sort
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)

# Reverse Order
thislist.reverse()
print(thislist)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']
[23, 50, 65, 82, 100]
[100, 82, 65, 50, 23]
[50, 65, 23, 82, 100]
['banana', 'cherry', 'Kiwi', 'Orange']
['Orange', 'Kiwi', 'cherry', 'banana']


## Copy Lists

In [53]:
thislist = ["apple", "banana", "cherry"]
mylist = thislist.copy()
print(mylist)

mylist = list(thislist)
print(mylist)

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry']


# Join Lists

In [ ]:
'''
1. +
2. .append() with for loop
3. .extend()
'''

## List Methods

In [ ]:
'''
Method	Description
append()	Adds an element at the end of the list
clear()	Removes all the elements from the list
copy()	Returns a copy of the list
count()	Returns the number of elements with the specified value
extend()	Add the elements of a list (or any iterable), to the end of the current list
index()	Returns the index of the first element with the specified value
insert()	Adds an element at the specified position
pop()	Removes the element at the specified position
remove()	Removes the item with the specified value
reverse()	Reverses the order of the list
sort()	Sorts the list
'''

# Tuples

In [57]:
'''
1. Can also contain different data types
2. Indexing like List
'''

thistuple = ("apple",)
print(type(thistuple))

#NOT a tuple
thistuple = ("apple")
print(type(thistuple))

<class 'tuple'>
<class 'str'>


## Change Tuple Values

In [59]:
'''
1. Convert to list
2. Add/Remove/Change
3. Convert back to tuple
'''

x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')


# Unpack Tuples

In [62]:
# extract the values back into variables

fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

# Using *
# varaibles < values

fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

(green, yellow, *red) = fruits

print(green)
print(yellow)
print(red)

fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

apple
banana
cherry
apple
banana
['cherry', 'strawberry', 'raspberry']
apple
['mango', 'papaya', 'pineapple']
cherry


## Join Tuples

In [ ]:
'''
Only assign to new variable
1. + 
2. *
'''

## Tuple Methods

In [ ]:
'''
count()	Returns the number of times a specified value occurs in a tuple
index()	Searches the tuple for a specified value and returns the position of where it was found
'''

# Python Sets

In [71]:
myset = {"apple", "banana", "cherry"}
set1 = {"abc", 34, True, 40, "male"}
thisset = set(("apple", "banana", "cherry")) # note the double round-brackets

print("banana" in thisset)

thisset.add("orange")
print(thisset)

tropical = {"pineapple", "mango", "papaya"}
thisset.update(tropical) # Add any Iterable
print(thisset)

thisset.remove("banana") # raise an error if item does not exists
print(thisset)

thisset.discard("banana") # does not raise an error if item does not exists
print(thisset)

x = thisset.pop()
print(x)
print(thisset)

thisset.clear()
del thisset
print(thisset)

True
{'orange', 'banana', 'cherry', 'apple'}
{'orange', 'papaya', 'pineapple', 'cherry', 'apple', 'banana', 'mango'}
{'orange', 'papaya', 'pineapple', 'cherry', 'apple', 'mango'}
{'orange', 'papaya', 'pineapple', 'cherry', 'apple', 'mango'}
orange
{'papaya', 'pineapple', 'cherry', 'apple', 'mango'}


NameError: name 'thisset' is not defined

## Joint Two Sets

In [75]:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

set1.update(set2)
print(set1)

# Keep ONLY the Duplicates
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.intersection_update(y)
print(x)

# Keep overlap

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection(y)
print(z)

# Keep All, but NOT the Duplicates

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.symmetric_difference_update(y)

print(x)

{1, 2, 3, 'a', 'b', 'c'}
{1, 2, 3, 'a', 'b', 'c'}
{'apple'}
{'apple'}
{'cherry', 'google', 'banana', 'microsoft'}


# Numpy

In [1]:
import numpy as np

In [4]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [3]:
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

'''

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [5]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [6]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [8]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [2]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [4]:
'''
Convert 1D array with 8 elements to 3D array with 2x2 elements:
'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [3]:
'''
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

Example
'''

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Join

In [6]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [8]:
'''
Join two 2-D arrays along rows (axis=1)
'''
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [11]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


## Split

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [15]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [23]:
arr = np.array([6, 7, 8, 9])

x1 = np.searchsorted(arr, 7,)
x2 = np.searchsorted(arr, 7, side='right')
print(x1)
print(x2)

1
2


In [24]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## Sort

In [25]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [26]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


## Filter

In [27]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [31]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [29]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
